language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer self-update

install:
    - composer install --no-interaction

script:
    - mkdir -p build/logs
    - phpunit -v --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
